version: '3.3'

services:
  backend:
    image: newspace-back
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "3000:3000"
    volumes:
      - /var/www/newartspace/backend/uploads/paintings:/app/uploads/paintings
    env_file:
      - .env
    command: ["yarn", "start:prod"]
    restart: unless-stopped

