apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/vsevolod-rusinskiy/newartspace-back:latest  # Указываем образ из GitHub Packages
          imagePullPolicy: Always  # Гарантируем загрузку последней версии образа
          ports:
            - containerPort: 3000
          env:
            - name: SQL_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SQL_DIALECT
            - name: SQL_LOGGING
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SQL_LOGGING
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: POSTGRES_NAME
      imagePullSecrets:
        - name: ghcr-io-secret  # Добавляем секрет для доступа к приватному образу