name: Master CI/CD

on:
  push:
    branches:
      - master

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier check
        run: yarn prettier-check

  deploy:
    needs: prettier-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/newartspace/backend

            echo -e "\e[34mStopping current containers...\e[0m"
            docker-compose down

            echo -e "\e[34mRestoring repository to the latest committed state...\e[0m"
            git restore .

            echo -e "\e[34mPulling latest changes from the repository...\e[0m"
            git pull origin master

            echo -e "\e[34mRunning database migrations...\e[0m"
            docker-compose exec backend yarn sequelize db:migrate --config src/config/config.js

            echo -e "\e[34mBuilding Docker images...\e[0m"
            docker-compose build

            echo -e "\e[34mStarting new containers...\e[0m"
            docker-compose up -d

