name: Master CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier check
        run: yarn prettier-check

  deploy:
    needs: prettier-check  # Выполнить развертывание только после успешной проверки кода
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with Docker Compose
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USERNAME@$SSH_HOST << 'EOF'
            cd /path/to/your/project
            docker-compose down
            docker-compose up -d --build
          EOF
          rm private_key.pem
